Traceback (most recent call last):
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 567, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=timeout))
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 83, in ensure_async
    result = await obj
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 968, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 72, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 51, in just_run
    return loop.run_until_complete(coro)
  File "/home/mikel/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 509, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 734, in async_execute_cell
    parent_msg_id, cell, exec_timeout, task_poll_output_msg
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 587, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/mikel/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 617, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
print('Tree map with data points clustered (this will take a while to run).')
lat = df['Y'].mean()
lon = df['X'].mean()
tree_map_mc = folium.Map(location=[lat,lon], zoom_start=12)
marker_cluster = MarkerCluster()
for row in df.itertuples():
    marker_cluster.add_child(folium.Marker(location=[row.Y,row.X], popup=row.AssetID, tooltip=row.species))
tree_map_mc.add_child(marker_cluster)
tree_map_mc
-------------------

